name: continuos-integration-checks
on:
  push:
    branches: [ main ]
jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install

      - name: Run eslint check
        run: npm run lint
      